#%RAML 0.8
title: internship_offer_api
version: 1.0
baseUri: http://localhost:8081/api/{version}
/alloffers:
  displayName: InsaShip get all offers from all companies
  get:
    description: Query all companies all internship offers
    responses:
      200:
        body:
         application/json:
          schema: |
              {
                "$schema": "http://json-schema.org/draft-04/schema#",
                "id": "http://jsonschema.net",
                "type": "object",
                "properties": {
                  "Offer": {
                    "id": "http://jsonschema.net/Offer",
                    "type": "object",
                    "properties": {
                      "ident": {
                        "id": "http://jsonschema.net/Offer/ident",
                        "type": "string"
                      },
                      "title": {
                        "id": "http://jsonschema.net/Offer/title",
                        "type": "string"
                      },
                      "description": {
                        "id": "http://jsonschema.net/Offer/description",
                        "type": "string"
                      }
                    },
                    "required": [
                      "ident",
                      "title",
                      "description"
                    ]
                  }
                },
                "required": [
                  "Offer"
                ]
              }
/companyoffers:
  displayName: InsaShip get all offers from a given companies
  get:
    description: Query all internship offers from a given company
    queryParameters:
      cpnId:
        type: string
        required: true
    responses:
      200:
        body:
         application/json:
          schema: |
              {
                "$schema": "http://json-schema.org/draft-04/schema#",
                "id": "http://jsonschema.net",
                "type": "object",
                "properties": {
                  "Offer": {
                    "id": "http://jsonschema.net/Offer",
                    "type": "object",
                    "properties": {
                      "ident": {
                        "id": "http://jsonschema.net/Offer/ident",
                        "type": "string"
                      },
                      "title": {
                        "id": "http://jsonschema.net/Offer/title",
                        "type": "string"
                      },
                      "description": {
                        "id": "http://jsonschema.net/Offer/description",
                        "type": "string"
                      }
                    },
                    "required": [
                      "ident",
                      "title",
                      "description"
                    ]
                  }
                },
                "required": [
                  "Offer"
                ]
              }
/search:
  displayName: InsaShip search for offers
  get:
    description: Query companies internship offers
    queryParameters:
      keyword:
        type: string
        required: true
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "Offer" :  {
                  "ident" : "cpnyId-offerId",
                  "title" : "offer title",
                  "description" : "offer description"
                  }
              }
            schema: |
              {
                "$schema": "http://json-schema.org/draft-04/schema#",
                "id": "http://jsonschema.net",
                "type": "object",
                "properties": {
                  "Offer": {
                    "id": "http://jsonschema.net/Offer",
                    "type": "object",
                    "properties": {
                      "ident": {
                        "id": "http://jsonschema.net/Offer/ident",
                        "type": "string"
                      },
                      "title": {
                        "id": "http://jsonschema.net/Offer/title",
                        "type": "string"
                      },
                      "description": {
                        "id": "http://jsonschema.net/Offer/description",
                        "type": "string"
                      }
                    },
                    "required": [
                      "ident",
                      "title",
                      "description"
                    ]
                  }
                },
                "required": [
                  "Offer"
                ]
              }
/singleoffer:
  displayName: InsaShip search for offers
  get:
    description: Get a single internship offer for a given companyId and an offerId
    queryParameters:
      cpnId:
        type: string
        required: true
      offerId:
        type: string
        required: true
    responses:
      200:
        body:
          application/json:
/sendmessage:
  displayName: InsaShip send message service
  get:
    description: Send a mail message for a given email and type
    queryParameters:
      email:
        type: string
        required: true
      type:
        type: integer
        required: true
    responses:
      200:
        body:
          application/json: